#!/bin/bash
# @author bfosberry
. gamekick_common

SLEEP_INTERVAL=5

function clear_server {
  $ETCDCTL_COMMAND rm --recursive $SERVER_ID 2> /dev/null
}

function clear_logs {
  rm -rf $DATA_FOLDER/logs/*
}

function clear_state {
  rm -rf $DATA_FOLDER/state/*
}

function get_action {
  error_regex="Key not found"
  ACTION_KEY=`$ETCDCTL_COMMAND ls /$SERVER_ID/actions 2> /dev/null | head -n 1`
  if [[ ! "$ACTION_KEY" =~ $error_regex  ]] && [[ ! "$ACTION_KEY" == "" ]]; then
    ACTION_VALUE=`$ETCDCTL_COMMAND get $ACTION_KEY 2> /dev/null`
    $ETCDCTL_COMMAND rm $ACTION_KEY 2> /dev/null
    ACTION_KEY=`echo "$ACTION_KEY" | sed -e "s/\/[a-z0-9A-Z_-]\+\/actions\///"`
  else
    ACTION_KEY=""
    ACTION_VALUE=""
  fi
}

function initialize_data_folder {
    mkdir -p "$DATA_FOLDER/state"
    mkdir -p "$DATA_FOLDER/logs"
    if [ -f "initialize_game_folder" ]; then
      initialize_game_folder
    fi
}

function dump_config {
  echo "" > $ENV_FILE
  for line in $($ETCDCTL_COMMAND ls /$SERVER_ID/config); do 
    key=`echo "$line" | sed -e "s/\/[a-z0-9A-Z_-]\+\/config\///"`
    value=`$ETCDCTL_COMMAND get $line 2> /dev/null`
    echo "$key=$value" >> $ENV_FILE
  done
}

if [ -z $SERVER_ID ]; then
  echo "No Server Id provided"
  exit 1
fi

dump_config

initialize_data_folder

if [ -f "install_components" ]; then
  install_components
fi

if [ -f "write_config" ]; then
  write_config
fi

game_server_action "start"

while [ true ]; do
  sleep $SLEEP_INTERVAL

  #could also use the status flag to startscript here
  if [ ! game_server_online ]; then
    echo "Server is down"
    set_info_value "status" "stopped"
    clear_server
    exit 1
  fi

  get_action

  if [ "$ACTION_KEY" != "" ]; then
    echo "Performing action $ACTION_KEY"
    if [ "$ACTION_KEY" == "halt" ]; then
      clear_server
      game_server_action "halt"
      exit 0
    elif [ "$ACTION_KEY" == "delete_logs" ]; then
      clear_logs
    elif [ "$ACTION_KEY" == "reset" ]; then
      game_server_action "stop"
      clear_server
      clear_logs
      clear_state
      initialize_data_folder
      game_server_action "start"
    elif [ "$ACTION_KEY" == "restart" ]; then
      game_server_action "stop"
      game_server_action "start"
    else
      game_server_action "$ACTION_KEY" "$ACTION_VALUE"
    fi
  fi
done
